### ISSUE TITLE
Update New Relic Lambda Extension Dependency to 2.3.7+

### ISSUE THREAD

**Issue by nc-wittj** [newrelic/newrelic-lambda-layers#161]
## Is your feature request related to a problem? Please describe.
https://github.com/newrelic/newrelic-lambda-extension/pull/95

## Feature Description
The [New Relic Lambda Extension dependency](https://github.com/newrelic/newrelic-lambda-layers/blob/1321b242948d70be3e451bbede0eb61f0f12bb68/libBuild.sh#L63) has gotten a couple versions [out of date](https://github.com/newrelic/newrelic-lambda-extension/releases). Update it to at least v2.3.7, so we can take advantage of [loading license keys from Parameter Store](https://github.com/newrelic/newrelic-lambda-extension/pull/95).

## Describe Alternatives
We need to manually publish our own build of the layer with the updated version, which doesn't seem ideal.

## Priority
Blocker

**Comment by barryhagan** [comment]
Also, your build pipeline is not doing what you think it is.

The [2.3.8 tagged release](https://github.com/newrelic/newrelic-lambda-layers/releases/tag/v2.3.8_extension) created a new extension layer, but it is still the 2.3.6 extension because of what @nc-wittj referenced in libBuild.sh.   Tagging new releases of the extension without updating libBuild.sh to that version does nothing.

There isn't a great way to figure out what is in version 30 of the layer without pulling it down and inspecting the contents:
```sh
LAYER_CONTENT_URL=$(aws lambda get-layer-version-by-arn --arn arn:aws:lambda:us-east-2:451483290750:layer:NewRelicLambdaExtension:30 --query Content.Location --output text)
curl $LAYER_CONTENT_URL -o nr-layer.zip
```

**Comment by iamemilio** [comment]
oops, that's my mistake there. I'll patch that up and ship new layers with the latest extension ASAP

**Comment by iamemilio** [comment]
It should be releasing shortly

**Comment by nc-wittj** [comment]
Thank you, @iamemilio! Everything looks to be in order now!

**Comment by juarezjaramillo** [comment]
@iamemilio quick question. I reviewed it again. The lambda layer was version 32 before your changes, and it's now v33 (`...:layer:NewRelicNodeJS18XARM64:33`).
However, after deploying using the Serverless plugin, I still see two things:
1. New Relic Logs UI shows that the pluing still is v2.3.6 (`plugin:newrelic-lambda-extension:2.3.6`)
2. Startup check still fails to recognize the handler since it's a mjs file (which was fixed in v2.3.8).

Is there something specific to fix it?

**Comment by iamemilio** [comment]
There is a bug in the extension, we forgot to bump the version to 2.3.8 internally https://github.com/newrelic/newrelic-lambda-extension/blob/3597702d8daf055fa1a95f4090261d243d11efc0/util/extension.go#L4

What I am not sure about is why it's unable to recognize the .mjs file. We updated the publish job to pull the extension binary from the 2.3.8 release, which contains the fix for mis files.

**Comment by barryhagan** [comment]
I'd also suggest that it would be helpful to include the commit hash and/or release tag in the description written to the layer so it would be possible to correlate layer versions to github releases.

https://github.com/newrelic/newrelic-lambda-layers/blob/master/libBuild.sh#L207

**Comment by juarezjaramillo** [comment]
> 

@barryhagan thanks for the detailed response!

**Comment by juarezjaramillo** [comment]
> @juarezjaramillo is trying to use a NodeJS layer, but those haven't been published since the changes to update the extension version to 2.3.8.
> 
> v33 of NewRelicNodeJS18XARM64 was published as part of [this release](https://github.com/newrelic/newrelic-lambda-layers/releases/tag/v10.4.1_nodejs) _before_ the extension fix.
> 
> You just need to tag another *_nodejs release to update those layers. The v34 layer will fix this as soon as it is created.


@barryhagan thanks for the detailed response!

**Comment by iamemilio** [comment]
Releasing the layers now!

**Comment by juarezjaramillo** [comment]
Thanks @iamemilio!
