### ISSUE TITLE
Python 3.7 layer broken (ImportModuleError)

### ISSUE THREAD

**Issue by shemanthdazn** [newrelic/newrelic-lambda-layers#167]
When using the new Python 3.7 compatible new relic layer (e.g. arn:aws:lambda:eu-central-1:451483290750:layer:NewRelicPython37:10), our application fails. When deploying [the Python example](https://github.com/newrelic/newrelic-lambda-layers/issues/159) and modifying the terraform code, I get the same error.

## Description
`[ERROR] Runtime.ImportModuleError: Unable to import module 'newrelic_lambda_wrapper': Failed to import module: main Traceback (most recent call last):`

## Steps to Reproduce

Deploy the lambda python example with the newest new relic layer and python 3.7 (see also https://github.com/newrelic/newrelic-lambda-extension/pull/157). Deployment then succeeds but testing fails with the above error.

## Expected Behaviour

It should be able to import the module

## Relevant Logs / Console output

`[ERROR] Runtime.ImportModuleError: Unable to import module 'newrelic_lambda_wrapper': Failed to import module 'app': No module named 'app'`

**Comment by hmstepanek** [comment]
This looks like a repeat of https://github.com/newrelic/newrelic-lambda-layers/issues/159 which has been fixed. The latest is 
arn:aws:lambda:eu-central-1:451483290750:layer:NewRelicPython37:110 where as the version listed in this issue is arn:aws:lambda:eu-central-1:451483290750:layer:NewRelicPython37:10. I just want to confirm that you are using the latest with arn arn:aws:lambda:eu-central-1:451483290750:layer:NewRelicPython37:110?
